### ISSUE TITLE
"make distcheck" fails with latest C++ inclusions

### ISSUE THREAD

**Issue by evanmiller** [libxls/libxls#56]
@QuLogic Would you mind taking a look?

```
$ make distcheck

... stuff compiles ...

  CXX      cplusplus/main.o
../../cplusplus/main.cpp:43:10: fatal error: 'XlsReader.h' file not found
#include "XlsReader.h"
         ^~~~~~~~~~~~~
1 error generated.
make[2]: *** [cplusplus/main.o] Error 1
make[1]: *** [all] Error 2
make: *** [distcheck] Error 1
```

I believe the Makefile.am needs to be updated - is `XlsReader.h` supposed to be installed or is it just for testing? If so, should it go in the regular include path or somewhere else? (I am really not familiar with C++ installation conventions.)

**Comment by QuLogic** [comment]
I don't know; I thought it was meant to be installed. The problem is not that it isn't installed though, it's that autotools didn't even include it in the dist tarball because it's unreferenced entirely.

If you want it installed, you can add it to `nobase_include_HEADERS`. I don't think there's much convention as to where to place it that differs much from the C conventions.

**Comment by evanmiller** [comment]
Ok thanks. There are likely ABI implications for building XlsReader.cpp into the main dylib so I'll distribute it without installing for now.
