### ISSUE TITLE
MinGW Compilation

### ISSUE THREAD

**Issue by nutsbox** [libxls/libxls#68]
Hi,

I find this library very good. However, I'm lost as how can this be compiled in Windows using MinGW. Also, can you provide how-to on how to generate a static version of the library.

Kudos and kind regards!

**Comment by wrycode** [comment]
Hi @nutsbox I'm also trying to figure this out. Static linking should work as usual once we figure out how to compile via MinGW. It doesn't help that their [website](http://www.mingw.org/) is broken right now. 
I see you're trying to compile from Windows, but I'm trying to cross-compile from Linux which is different (but similar). I have it sort of working with this:

```bash
ac_cv_func_realloc_0_nonnull=yes ac_cv_func_malloc_0_nonnull=yes ./configure --host=x86_64-w64-mingw32 &&
PKG_CONFIG_PATH=/usr/x86_64-w64-mingw32/sys-root/mingw/lib/pkgconfig mingw64-make install"
```

This library isn't written with portable code which is why you need the `ac_cv_func_realloc_0_nonnull=yes` and `ac_cv_func_malloc_0_nonnull=yes ` environment variables set.

**Comment by wrycode** [comment]
>This library isn't written with portable code

Actually, this might not be true and the malloc thing might be a problem on my end. 

Just saw this line in the readme:
>Continuous integration tests on Mac, Linux, and Windows

So the library *can* build for Windows. It would be awesome if the authors could point us in the right direction to compile it using MinGW.

**Comment by wrycode** [comment]
I'm no longer using this library, but I thought I'd mention what worked for me.

- configure and make with `LDFLAGS="-all-static"`
- visit the src/ directory and create a new archive like this: `ar rc libxls.a *.o *.lo`
- index the archive: `ranlib libxls.a`
- use these flags in the GCC command: ` -Ilibxls-1.5.2/include/ -Ilibxls-1.5.2/include/libxls/` and add the .a file to the command

I also found that the example in the README is broken in at least one way: it refers to ` xl_WorkSheet` when the correct type is `xlsWorkSheet`.

**Comment by shashi4u** [comment]
I have mentioned a workaround for Cygwin64 here #70
I have also attached my version of Visual Studio 2015 solution there

**Comment by evanmiller** [comment]
There are 32-bit Cygwin instructions here:

https://github.com/libxls/libxls/blob/master/INSTALL

If you have additional Windows instructions to contribute, please open a pull request.

Static library options are documented `./configure --help` (`./configure --enable-static`)
